### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by mavizz** [aigenseer/qr-scanner-redirect#7]
I use with iphone x the camera is freeze. How can i fix that?

**Comment by aigenseer** [comment]
Hallo @mavizz,

Have you any error screen oder error message?

**Comment by mavizz** [comment]
No error message 
It work with camera in computer . but in mobile not work

**Comment by aigenseer** [comment]
Hallo @mavizz,

I updated the plugin to the version 1.0.4. Please can you test it with your device.

**Comment by mavizz** [comment]
Thats Work! 👍 Thank You somuch

**Comment by richard1st** [comment]
Hi! grate work!
But  version 1.0.4. still freezes on my iphone xs max pro

**Comment by rodeista** [comment]
Hi, same problem here, Android OK, but iPhone SE (old one) freezes. However great job, thank you!

**Comment by aigenseer** [comment]
Hi, i added a fix for the ios problem. I hope the problem has now been resolved.
